@baseUrl = http://localhost:3000

GET {{baseUrl}}/hello HTTP/1.1
Content-Type: application/json

###
POST {{baseUrl}}/sortnum HTTP/1.1
Content-Type: application/json

{
  "nums": "2,35,6,4,9"
}

###
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  # "name": "",
  # "password": "Admin&8181",
  "name": "admin",
  "password": "Admin&8181"
}